# Generated by Django 4.0.4 on 2022-04-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ad_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='ramnk',
            new_name='rank',
        ),
    ]
