# Generated by Django 4.0.4 on 2022-04-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_ramnk_slider_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='ramnk',
            new_name='rank',
        ),
    ]
